window.OwnerData = {
  metrics: [
    { label: "Total Enrolled", value: "1,284", change: "12% from last term", tone: "good" },
    { label: "Active Courses", value: "42", change: "Course catalog", tone: "neutral" },
    { label: "Average Capacity", value: "88%", change: "5 cohorts full", tone: "good" },
    { label: "Pending Actions", value: "17", change: "Needs review", tone: "warn" },
  ],
  branches: [
    { name: "District 1 Campus", students: 168, revenue: 36200, occupancy: 91 },
    { name: "Riverside Campus", students: 142, revenue: 27400, occupancy: 83 },
    { name: "West Studio", students: 118, revenue: 20600, occupancy: 76 },
  ],
  classes: [
    {
      code: "MATH-10A",
      name: "Advanced Mathematics - Grade 10",
      teacher: "N. Minh Khoa",
      campus: "District 1 Campus",
      students: 24,
      capacity: 28,
      schedule: "Tue & Thu, 4:30 PM",
      status: "Healthy",
    },
    {
      code: "IELTS-7B",
      name: "IELTS Foundation Band 7",
      teacher: "A. Thu Nguyen",
      campus: "Riverside Campus",
      students: 18,
      capacity: 20,
      schedule: "Mon & Wed, 6:30 PM",
      status: "Full Soon",
    },
    {
      code: "PHY-11C",
      name: "Physics Lab - Grade 11",
      teacher: "D. Hoang Pham",
      campus: "West Studio",
      students: 12,
      capacity: 18,
      schedule: "Sat, 9:00 AM",
      status: "Needs Fill",
    },
    {
      code: "ENG-08A",
      name: "Academic English - Grade 8",
      teacher: "L. Sarah Tran",
      campus: "District 1 Campus",
      students: 26,
      capacity: 26,
      schedule: "Fri, 5:30 PM",
      status: "At Capacity",
    },
  ],
  accounts: [
    {
      name: "Sarah Jenkins",
      joined: "Oct 2023",
      role: "Teacher",
      email: "s.jenkins@atelier.edu",
      phone: "+1 (555) 012-3456",
      status: "Active",
      avatar: "SJ",
      color: "#f5b44b",
    },
    {
      name: "Marcus Thorne",
      joined: "Jan 2024",
      role: "Staff",
      email: "m.thorne@atelier.edu",
      phone: "+1 (555) 987-6543",
      status: "Active",
      avatar: "MT",
      color: "#0f4c5c",
    },
    {
      name: "Elena Rodriguez",
      joined: "Dec 2023",
      role: "Student",
      email: "elena.r@gmail.com",
      phone: "+1 (555) 234-5678",
      status: "Inactive",
      avatar: "ER",
      color: "#3b2f4a",
    },
    {
      name: "David Chen",
      joined: "Nov 2023",
      role: "Teacher",
      email: "d.chen@atelier.edu",
      phone: "+1 (555) 456-7890",
      status: "Active",
      avatar: "DC",
      color: "#27364f",
    },
    {
      name: "Aisha Miller",
      joined: "Feb 2024",
      role: "Staff",
      email: "a.miller@atelier.edu",
      phone: "+1 (555) 765-4321",
      status: "Active",
      avatar: "AM",
      color: "#2e9c95",
    },
  ],
  courses: [
    {
      id: "course-calculus-2",
      code: "MATH-204",
      name: "Advanced Calculus II",
      subject: "Mathematics",
      level: "University Prep",
      prerequisites: ["Calculus I", "Algebra III"],
      status: "Active",
      tone: "math",
      instructor: "N. Minh Khoa",
      duration: "12 weeks",
      sessions: 10,
      enrolled: 32,
      capacity: 36,
      syllabus: "advanced-calculus-ii.pdf",
      summary:
        "A rigorous continuation of differential and integral calculus with applications in analytic geometry and physical systems.",
    },
    {
      id: "course-molecular-biology",
      code: "SCI-312",
      name: "Molecular Biology",
      subject: "Science",
      level: "Grade 12",
      prerequisites: ["Bio 101"],
      status: "Active",
      tone: "science",
      instructor: "D. Hoang Pham",
      duration: "10 weeks",
      sessions: 8,
      enrolled: 24,
      capacity: 28,
      syllabus: "molecular-biology-lab.docx",
      summary:
        "Students investigate DNA, protein synthesis, genetics, and laboratory reasoning through guided inquiry.",
    },
    {
      id: "course-creative-writing",
      code: "ENG-118",
      name: "Creative Writing Workshop",
      subject: "English",
      level: "All Levels",
      prerequisites: [],
      status: "Inactive",
      tone: "english",
      instructor: "L. Sarah Tran",
      duration: "6 weeks",
      sessions: 6,
      enrolled: 14,
      capacity: 22,
      syllabus: "creative-writing-workshop.pdf",
      summary:
        "A workshop-based course for drafting, peer critique, revision, and portfolio preparation across genres.",
    },
    {
      id: "course-intro-python",
      code: "CS-101",
      name: "Intro to Python",
      subject: "Computer Science",
      level: "Beginner",
      prerequisites: ["Logic 101"],
      status: "Active",
      tone: "tech",
      instructor: "Aisha Miller",
      duration: "8 weeks",
      sessions: 8,
      enrolled: 29,
      capacity: 30,
      syllabus: "intro-to-python.pptx",
      summary:
        "A practical programming course covering syntax, control flow, functions, and small automation projects.",
    },
  ],
  teachers: [
    { name: "N. Minh Khoa", subject: "Mathematics", load: 86, rating: 4.8 },
    { name: "A. Thu Nguyen", subject: "English", load: 78, rating: 4.9 },
    { name: "D. Hoang Pham", subject: "Physics", load: 64, rating: 4.7 },
    { name: "L. Sarah Tran", subject: "English", load: 92, rating: 4.8 },
  ],
  cashflow: [
    { month: "Jan", value: 62400 },
    { month: "Feb", value: 70100 },
    { month: "Mar", value: 76850 },
    { month: "Apr", value: 81200 },
    { month: "May", value: 84600 },
  ],
  revenueSummary: {
    month: 84600,
    lastMonth: 81200,
    collected: 77420,
    outstanding: 7180,
    refunds: 1240,
    forecast: 90200,
  },
};
