window.StaffData = {
  metrics: [
    { label: "Total Students", value: "432", note: "+12 this month", tone: "good" },
    { label: "Active Classes", value: "24", note: "84% capacity", tone: "neutral" },
    { label: "Attendance Today", value: "92.4%", note: "-1.2% from avg", tone: "bad" },
    { label: "Pending Requests", value: "8", note: "5 Absences, 3 Staff", tone: "neutral" },
  ],
  utilization: [
    { day: "Mon", value: 62 },
    { day: "Tue", value: 76 },
    { day: "Wed", value: 88 },
    { day: "Thu", value: 72 },
    { day: "Fri", value: 54 },
    { day: "Sat", value: 40 },
    { day: "Sun", value: 22 },
  ],
  liveClasses: [
    { name: "Advanced Calculus", room: "Room 302", teacher: "Dr. Aris Thorne", status: "Live" },
    { name: "Physics II: Mechanics", room: "Lab Alpha", teacher: "Prof. Elena Vance", status: "Live" },
    { name: "Macroeconomics", room: "Hall 10", teacher: "Julian S. Reed", status: "Live" },
  ],
  rooms: [
    { name: "Room 301", capacity: 30, status: "Available" },
    { name: "Lab 402", capacity: 24, status: "Available" },
    { name: "Hall B", capacity: 42, status: "Available" },
    { name: "Digital Hub 1", capacity: 28, status: "Available" },
    { name: "Private Office 2", capacity: 6, status: "Reserved" },
  ],
  facilities: [
    {
      id: "room-301",
      name: "Room 301",
      location: "Science Wing • Level 3",
      capacity: 30,
      status: "In Use",
      equipment: ["Projector", "Whiteboard", "Lab Tools"],
      image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "lab-104",
      name: "Lab 104",
      location: "Tech Center • Ground Floor",
      capacity: 24,
      status: "Available",
      equipment: ["Projector", "Whiteboard", "Lab Tools"],
      image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "seminar-02",
      name: "Seminar 02",
      location: "Arts Plaza • Level 1",
      capacity: 12,
      status: "In Use",
      equipment: ["Projector", "Whiteboard", "N/A"],
      image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "auditorium-b",
      name: "Auditorium B",
      location: "Main Hall • North Entrance",
      capacity: 120,
      status: "Available",
      equipment: ["Projector", "Whiteboard", "N/A"],
      image: "https://images.unsplash.com/photo-1497366412874-3415097a27e7?auto=format&fit=crop&w=900&q=80",
    },
  ],
  staffTeachers: [
    { id: "teacher-sterling", name: "Prof. Sterling", subject: "Mathematics", department: "Advanced Mathematics", email: "sterling@techroom.edu", phone: "+1 (555) 310-2210", load: 6, status: "Available", avatar: "PS" },
    { id: "teacher-aris", name: "Dr. Aris", subject: "Physics", department: "Physics", email: "aris@techroom.edu", phone: "+1 (555) 310-2211", load: 4, status: "Available", avatar: "DA" },
    { id: "teacher-vance", name: "Prof. Elena Vance", subject: "Science", department: "Science", email: "vance@techroom.edu", phone: "+1 (555) 310-2212", load: 5, status: "Available", avatar: "EV" },
    { id: "teacher-bennet", name: "Ms. Bennet", subject: "English", department: "Literature", email: "bennet@techroom.edu", phone: "+1 (555) 310-2213", load: 2, status: "Busy", avatar: "MB" },
    { id: "teacher-davis", name: "Dr. Davis", subject: "Computer Science", department: "Computer Science", email: "davis@techroom.edu", phone: "+1 (555) 310-2214", load: 5, status: "Available", avatar: "DD" },
    { id: "teacher-jenkins", name: "Sarah Jenkins", subject: "Digital Illustration", department: "Design", email: "jenkins@techroom.edu", phone: "+1 (555) 310-2215", load: 8, status: "Active", avatar: "SJ" },
  ],
  timetableSessions: [
    {
      id: "algorithms-monday",
      day: "Mon",
      date: "12",
      start: "09:00",
      end: "10:30",
      category: "Computer Science 101",
      title: "Algorithms & Logic",
      room: "Lab 402",
      students: 24,
      tone: "teal",
    },
    {
      id: "linear-algebra",
      day: "Tue",
      date: "13",
      start: "10:00",
      end: "11:30",
      category: "Advanced Mathematics",
      title: "Linear Algebra Refresher",
      room: "Hall B",
      students: 32,
      tone: "outline",
    },
    {
      id: "lunch-break",
      day: "Wed",
      date: "14",
      start: "11:00",
      end: "12:00",
      category: "Lunch Break",
      title: "Faculty Lunch Break",
      room: "",
      students: 0,
      tone: "muted",
    },
    {
      id: "staff-workshop",
      day: "Wed",
      date: "14",
      start: "14:00",
      end: "15:00",
      category: "Room Conflict",
      title: "Staff Workshop",
      room: "16:30 - 17:30",
      students: 0,
      tone: "danger",
    },
    {
      id: "thesis-review",
      day: "Thu",
      date: "15",
      start: "09:00",
      end: "12:00",
      category: "Research & Mentoring",
      title: "Post-Grad Thesis Review",
      room: "Private Office 2",
      students: 3,
      tone: "side",
    },
    {
      id: "agile-methodologies",
      day: "Fri",
      date: "16",
      start: "10:00",
      end: "12:00",
      category: "Software Engineering",
      title: "Agile Methodologies",
      room: "Digital Hub 1",
      students: 28,
      tone: "teal",
    },
  ],
  notifications: [
    { title: "Emergency Absence: Sarah Miller", body: "Class: English Literature - Tutor replacement requested.", time: "14 mins ago", tone: "danger" },
    { title: "Monthly Reports Generated", body: "Academic performance reports for March are now available.", time: "1 hour ago", tone: "success" },
    { title: "Staff Meeting: Curriculum Review", body: "Scheduled for Friday at 3:00 PM in Conference Room B.", time: "3 hours ago", tone: "info" },
  ],
  courseRules: {
    mathematics: {
      label: "Mathematics",
      sessionsPerWeek: 3,
      note: "Advanced math tracks require 3 sessions per week.",
    },
    physics: {
      label: "Physics",
      sessionsPerWeek: 2,
      note: "Physics courses include 1 theory session and 1 lab session per week.",
    },
    english: {
      label: "English",
      sessionsPerWeek: 2,
      note: "English cohorts meet twice weekly for reading and workshop blocks.",
    },
    computerScience: {
      label: "Computer Science",
      sessionsPerWeek: 3,
      note: "Coding courses require 2 lecture sessions and 1 practice lab per week.",
    },
  },
  classes: [
    {
      id: "advanced-algorithms",
      name: "Advanced Algorithm and Logic",
      course: "Mathematics",
      code: "Advanced Computing • U21",
      startDate: "Aug 12, 2024",
      teacher: "Prof. Sterling",
      status: "Ongoing",
      icon: "math",
      enrolled: 42,
      room: "Room 302",
      schedule: "Mon, Wed, Fri • 09:00 - 10:30",
      teachers: [
        { name: "Dr. Julian Vance", role: "Lead Lecturer", avatar: "JV", color: "#48636b" },
        { name: "Prof. Sarah Chen", role: "Module Coordinator", avatar: "SC", color: "#7ca095" },
      ],
      students: [
        { id: "ST-2023-0012", name: "Alex Mercer", initials: "AM", enrollDate: "Sep 12, 2023", status: "Active" },
        { id: "ST-2023-0455", name: "Elena Wright", initials: "EW", enrollDate: "Sep 14, 2023", status: "Active" },
        { id: "ST-2023-0089", name: "Jordan Kales", initials: "JK", enrollDate: "Sep 15, 2023", status: "On Leave" },
        { id: "ST-2023-0912", name: "Sanya Nair", initials: "SN", enrollDate: "Sep 15, 2023", status: "Active" },
      ],
    },
    { id: "physics-lab", name: "Physics & Lab", course: "Physics", code: "Science • P14", startDate: "Sep 01, 2024", teacher: "Dr. Aris", status: "Ongoing", icon: "science", enrolled: 36, room: "Lab Alpha", schedule: "Tue, Thu • 13:00 - 14:30", teachers: [], students: [] },
    { id: "intro-literature", name: "Intro to Literature", course: "English", code: "Humanities • E08", startDate: "Oct 15, 2024", teacher: "Ms. Bennet", status: "Open", icon: "book", enrolled: 28, room: "Hall 4", schedule: "Wed • 15:00 - 17:00", teachers: [], students: [] },
    { id: "modern-history", name: "Modern History", course: "History", code: "History • H10", startDate: "Jun 10, 2024", teacher: "Dr. Harris", status: "Completed", icon: "history", enrolled: 31, room: "Room 110", schedule: "Fri • 08:30 - 10:00", teachers: [], students: [] },
    { id: "python-scripting", name: "Python Scripting", course: "Computer Science", code: "Computing • C05", startDate: "Jul 22, 2024", teacher: "Dr. Davis", status: "Cancelled", icon: "tech", enrolled: 0, room: "Lab Beta", schedule: "Cancelled", teachers: [], students: [] },
  ],
  availableStudents: [
    { id: "ST-2024-1101", name: "Mina Park", initials: "MP", grade: "U17", email: "mina.park@student.techroom.edu", phone: "+1 (555) 201-1101", guardian: "J. Park", joined: "Mar 02, 2024", status: "Active", classId: "advanced-algorithms" },
    { id: "ST-2024-1102", name: "Kai Bennett", initials: "KB", grade: "U17", email: "kai.bennett@student.techroom.edu", phone: "+1 (555) 201-1102", guardian: "N. Bennett", joined: "Mar 04, 2024", status: "Active", classId: "physics-lab" },
    { id: "ST-2024-1103", name: "Nora Ellis", initials: "NE", grade: "U18", email: "nora.ellis@student.techroom.edu", phone: "+1 (555) 201-1103", guardian: "P. Ellis", joined: "Mar 07, 2024", status: "Active", classId: "intro-literature" },
    { id: "ST-2024-1104", name: "Theo Grant", initials: "TG", grade: "U16", email: "theo.grant@student.techroom.edu", phone: "+1 (555) 201-1104", guardian: "M. Grant", joined: "Mar 11, 2024", status: "Active", classId: "modern-history" },
    { id: "ST-2024-1105", name: "Linh Tran", initials: "LT", grade: "U17", email: "linh.tran@student.techroom.edu", phone: "+1 (555) 201-1105", guardian: "H. Tran", joined: "Mar 15, 2024", status: "On Leave", classId: "advanced-algorithms" },
    { id: "ST-2024-1106", name: "Hana Mori", initials: "HM", grade: "U18", email: "hana.mori@student.techroom.edu", phone: "+1 (555) 201-1106", guardian: "K. Mori", joined: "Mar 20, 2024", status: "Active", classId: "physics-lab" },
  ],
  makeupStudents: [
    { id: "MK-2024-0201", name: "Rina Cole", initials: "RC", reason: "Missed lab session", status: "Eligible" },
    { id: "MK-2024-0202", name: "Oscar Minh", initials: "OM", reason: "Approved absence", status: "Eligible" },
    { id: "MK-2024-0203", name: "Bella Hart", initials: "BH", reason: "Schedule conflict", status: "Pending" },
    { id: "MK-2024-0204", name: "Tuan Le", initials: "TL", reason: "Medical leave", status: "Eligible" },
  ],
  makeupRequests: [
    { id: "REQ-1001", student: "Julianne Devis", initials: "JD", originalClass: "ADV-Painting II", missedDate: "Oct 12, 2023", status: "Approved Absence", subject: "Design", level: "Intermediate (L3)" },
    { id: "REQ-1002", student: "Marcus Holloway", initials: "MH", originalClass: "DIG-Illustration", missedDate: "Oct 14, 2023", status: "Approved Absence", subject: "Computer Science", level: "Intermediate (L3)" },
    { id: "REQ-1003", student: "Lydia Wu", initials: "LW", originalClass: "WTR-Color III", missedDate: "Oct 15, 2023", status: "Approved Absence", subject: "English", level: "Foundation (L1)" },
  ],
  makeupAvailableSessions: [
    { id: "MKC-1", code: "CS101-B", topic: "Data Structure: Linked List", date: "Oct 14, 2023", time: "10:00 AM - 12:00 PM", room: "Lab 402", seats: "4 / 12", subject: "Computer Science", level: "Intermediate (L3)" },
    { id: "MKC-2", code: "CS101-C", topic: "Algorithm Practice Lab", date: "Oct 16, 2023", time: "02:00 PM - 04:00 PM", room: "Digital Hub 1", seats: "7 / 14", subject: "Computer Science", level: "Intermediate (L3)" },
    { id: "MKC-3", code: "ART210-A", topic: "Studio Critique: Composition", date: "Oct 17, 2023", time: "09:00 AM - 11:00 AM", room: "Seminar 02", seats: "3 / 10", subject: "Design", level: "Intermediate (L3)" },
    { id: "MKC-4", code: "ENG112-D", topic: "Writing Revision Workshop", date: "Oct 18, 2023", time: "01:00 PM - 03:00 PM", room: "Hall B", seats: "5 / 16", subject: "English", level: "Foundation (L1)" },
  ],
  dispatches: [
    { id: "DSP-1", title: "Emergency: Campus Closure", body: "Heavy snowfall anticipated. All afternoon sessions will move online.", recipients: "Class: All Students", sentAt: "Oct 24, 2023 • 08:15 AM", status: "Sent", type: "Emergency" },
    { id: "DSP-2", title: "Grade 10 Math: Midterm Prep", body: "Review guidelines for the upcoming assessment are now available.", recipients: "Class: Grade 10 Math", sentAt: "Oct 23, 2023 • 02:45 PM", status: "Sent", type: "Academic" },
    { id: "DSP-3", title: "Faculty Meeting Agenda", body: "Discussion points for the monthly academic sync have been posted.", recipients: "All Teachers", sentAt: "Oct 26, 2023 • 09:00 AM", status: "Scheduled", type: "Faculty" },
  ],
  studentsForNewClass: ["Alex Rivera (U17)", "Sarah Chen (U17)", "Jordan Smythe (U17)"],
};
