window.TeacherData = {
  students: [
    {
      name: "Julian Vance",
      id: "40221",
      attendance: 98,
      progress: 92,
      status: "Active",
      avatar: "J",
      color: "#f39b54",
      photo: "JV",
      feedback: {
        attitude: "Attentive",
        progress: "Good",
        comments:
          "Julian demonstrated a strong grasp of quadratic equations today. He was able to solve complex problems independently but struggled slightly with the word problems at the end of the session. We will focus more on contextual application next week.",
      },
    },
    {
      name: "Maya Sterling",
      id: "40225",
      attendance: 84,
      progress: 76,
      status: "Active",
      avatar: "M",
      color: "#3bc1aa",
      photo: "MS",
      feedback: {
        attitude: "Attentive",
        progress: "Good",
        comments:
          "Maya participated actively and showed steady improvement with trigonometric identities. She should keep practicing multi-step simplification.",
      },
    },
    {
      name: "Liam O'Connell",
      id: "40230",
      attendance: 72,
      progress: 45,
      status: "Inactive",
      avatar: "L",
      color: "#5fb4c8",
      photo: "LO",
      feedback: {
        attitude: "Distracted",
        progress: "Needs Improvement",
        comments:
          "Liam needs extra support with foundational algebra before moving deeper into logarithmic functions.",
      },
    },
    {
      name: "Chloe Zhang",
      id: "40238",
      attendance: 100,
      progress: 88,
      status: "Active",
      avatar: "C",
      color: "#e48788",
      photo: "CZ",
      feedback: {
        attitude: "Attentive",
        progress: "Excellent",
        comments:
          "Chloe completed all assigned work with clear reasoning and helped explain alternate solution paths during discussion.",
      },
    },
    { name: "Ethan Rivera", id: "40242", attendance: 91, progress: 79, status: "Active", avatar: "E", color: "#a78bfa", photo: "ER", feedback: { attitude: "Steady", progress: "Good", comments: "Ethan is consistent and prepared. Continue reinforcing proof notation." } },
    { name: "Sophia Chen", id: "40247", attendance: 67, progress: 53, status: "Active", avatar: "S", color: "#f472b6", photo: "SC", feedback: { attitude: "Steady", progress: "Needs Improvement", comments: "Sophia should review core formulas before each session." } },
    { name: "Noah Patel", id: "40251", attendance: 88, progress: 94, status: "Active", avatar: "N", color: "#34d399", photo: "NP", feedback: { attitude: "Attentive", progress: "Excellent", comments: "Noah works quickly and accurately. Add extension problems next week." } },
    { name: "Emma Thompson", id: "40256", attendance: 45, progress: 38, status: "Inactive", avatar: "E", color: "#fb923c", photo: "ET", feedback: { attitude: "Distracted", progress: "Needs Improvement", comments: "Emma needs a recovery plan and consistent attendance." } },
    { name: "James Kim", id: "40260", attendance: 95, progress: 91, status: "Active", avatar: "J", color: "#60a5fa", photo: "JK", feedback: { attitude: "Attentive", progress: "Excellent", comments: "James shows strong conceptual fluency." } },
    { name: "Olivia Garcia", id: "40264", attendance: 78, progress: 62, status: "Active", avatar: "O", color: "#c084fc", photo: "OG", feedback: { attitude: "Steady", progress: "Good", comments: "Olivia is improving but should slow down on word problems." } },
    { name: "Benjamin Lee", id: "40269", attendance: 82, progress: 71, status: "Active", avatar: "B", color: "#2dd4bf", photo: "BL", feedback: { attitude: "Steady", progress: "Good", comments: "Benjamin is building confidence with graph interpretation." } },
    { name: "Ava Martinez", id: "40273", attendance: 56, progress: 44, status: "Inactive", avatar: "A", color: "#f87171", photo: "AM", feedback: { attitude: "Distracted", progress: "Needs Improvement", comments: "Ava needs a short daily practice routine." } },
    { name: "Lucas Brown", id: "40278", attendance: 93, progress: 86, status: "Active", avatar: "L", color: "#38bdf8", photo: "LB", feedback: { attitude: "Attentive", progress: "Good", comments: "Lucas is ready for more challenging applications." } },
    { name: "Mia Wilson", id: "40282", attendance: 74, progress: 69, status: "Active", avatar: "M", color: "#a3e635", photo: "MW", feedback: { attitude: "Steady", progress: "Good", comments: "Mia should keep practicing timed exercises." } },
    { name: "Henry Davis", id: "40287", attendance: 89, progress: 83, status: "Active", avatar: "H", color: "#fbbf24", photo: "HD", feedback: { attitude: "Attentive", progress: "Good", comments: "Henry explains reasoning well in small groups." } },
    { name: "Isabella Nguyen", id: "40291", attendance: 63, progress: 51, status: "Inactive", avatar: "I", color: "#e879f9", photo: "IN", feedback: { attitude: "Steady", progress: "Needs Improvement", comments: "Isabella needs extra review on prerequisites." } },
    { name: "Alexander White", id: "40296", attendance: 97, progress: 95, status: "Active", avatar: "A", color: "#22c55e", photo: "AW", feedback: { attitude: "Attentive", progress: "Excellent", comments: "Alexander is performing at an advanced level." } },
    { name: "Charlotte Harris", id: "40300", attendance: 71, progress: 58, status: "Active", avatar: "C", color: "#06b6d4", photo: "CH", feedback: { attitude: "Steady", progress: "Needs Improvement", comments: "Charlotte should focus on accuracy before speed." } },
    { name: "Daniel Clark", id: "40305", attendance: 86, progress: 77, status: "Active", avatar: "D", color: "#f59e0b", photo: "DC", feedback: { attitude: "Steady", progress: "Good", comments: "Daniel is improving steadily." } },
    { name: "Amelia Lewis", id: "40309", attendance: 52, progress: 41, status: "Inactive", avatar: "A", color: "#d946ef", photo: "AL", feedback: { attitude: "Distracted", progress: "Needs Improvement", comments: "Amelia needs structured review and follow-up." } },
    { name: "Matthew Robinson", id: "40314", attendance: 94, progress: 90, status: "Active", avatar: "M", color: "#10b981", photo: "MR", feedback: { attitude: "Attentive", progress: "Excellent", comments: "Matthew completes work with strong accuracy." } },
    { name: "Harper Walker", id: "40318", attendance: 69, progress: 55, status: "Active", avatar: "H", color: "#0ea5e9", photo: "HW", feedback: { attitude: "Steady", progress: "Needs Improvement", comments: "Harper should review missed questions after class." } },
    { name: "David Hall", id: "40323", attendance: 81, progress: 74, status: "Active", avatar: "D", color: "#8b5cf6", photo: "DH", feedback: { attitude: "Steady", progress: "Good", comments: "David is consistent and asks useful questions." } },
    { name: "Evelyn Allen", id: "40327", attendance: 77, progress: 65, status: "Active", avatar: "E", color: "#ec4899", photo: "EA", feedback: { attitude: "Steady", progress: "Good", comments: "Evelyn should keep building confidence with proofs." } },
  ],
  materials: [
    { title: "Calculus Foundations: Limits & Continuity", type: "pdf", size: "4.2 MB", added: "OCT 12, 2023" },
    { title: "Interactive Desmos Graph: Unit Circle", type: "link", size: "", added: "OCT 10, 2023" },
    { title: "Homework Sheet 04: Trigonometric Identities", type: "doc", size: "850 KB", added: "OCT 08, 2023" },
    { title: "Midterm Exam Review: Semester A", type: "pdf", size: "12.5 MB", added: "OCT 05, 2023" },
    { title: "Visualizing Derivatives - 3Blue1Brown", type: "link", size: "", added: "OCT 02, 2023" },
  ],
  assignments: [
    { title: "Quadratic Equations Practice", posted: "Oct 12", deadline: "Oct 24, 11:59 PM", submitted: 24, total: 28, urgent: true },
    { title: "Trigonometry Basics Quiz", posted: "Oct 05", deadline: "Oct 15, 11:59 PM", submitted: 28, total: 28, urgent: false },
    { title: "Logarithmic Functions HW", posted: "Oct 26", deadline: "Oct 28", submitted: 0, total: 28, urgent: false },
    { title: "Geometry Final Project Phase 1", posted: "Oct 18", deadline: "Nov 01, 11:59 PM", submitted: 12, total: 28, urgent: true },
  ],
  sessions: [
    { date: "Oct 24, 2023", day: "Tuesday", time: "4:30 PM", status: "Completed", action: "View Roster" },
    { date: "Oct 26, 2023", day: "Thursday", time: "4:30 PM", status: "In Progress", action: "Take Attendance", current: true, today: true },
    { date: "Oct 31, 2023", day: "Tuesday", time: "4:30 PM", status: "Scheduled", action: null },
    { date: "Nov 02, 2023", day: "Thursday", time: "4:30 PM", status: "Scheduled", action: null },
  ],
  weekDays: [
    { label: "MON", date: 14 },
    { label: "TUE", date: 15 },
    { label: "WED", date: 16, today: true },
    { label: "THU", date: 17 },
    { label: "FRI", date: 18 },
  ],
  timeSlots: ["08:00 AM", "09:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "01:00 PM", "02:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "06:00 PM", "07:00 PM"],
  timetableEvents: [
    { id: "math-monday", title: "Advanced Mathematics", day: 0, startHour: 9, startMinute: 0, durationMinutes: 90, location: "Room 301", students: "12 Enrolled" },
    { id: "art-history", title: "Art History", day: 1, startHour: 14, startMinute: 0, durationMinutes: 90, location: "Studio B", students: "18 Enrolled" },
    { id: "math-thursday", title: "Advanced Mathematics", day: 3, startHour: 16, startMinute: 30, durationMinutes: 90, location: "Room 301", students: "12 Enrolled", active: true },
  ],
};
