window.TeacherData = {
  students: [
    {
      name: "Julian Vance",
      id: "40221",
      attendance: 98,
      progress: 92,
      status: "Active",
      avatar: "J",
      color: "#f39b54",
      photo: "JV",
      feedback: {
        attitude: "Attentive",
        progress: "Good",
        comments:
          "Julian demonstrated a strong grasp of quadratic equations today. He was able to solve complex problems independently but struggled slightly with the word problems at the end of the session. We will focus more on contextual application next week.",
      },
    },
    {
      name: "Maya Sterling",
      id: "40225",
      attendance: 84,
      progress: 76,
      status: "Active",
      avatar: "M",
      color: "#3bc1aa",
      photo: "MS",
      feedback: {
        attitude: "Attentive",
        progress: "Good",
        comments:
          "Maya participated actively and showed steady improvement with trigonometric identities. She should keep practicing multi-step simplification.",
      },
    },
    {
      name: "Liam O'Connell",
      id: "40230",
      attendance: 72,
      progress: 45,
      status: "Inactive",
      avatar: "L",
      color: "#5fb4c8",
      photo: "LO",
      feedback: {
        attitude: "Distracted",
        progress: "Needs Improvement",
        comments:
          "Liam needs extra support with foundational algebra before moving deeper into logarithmic functions.",
      },
    },
    {
      name: "Chloe Zhang",
      id: "40238",
      attendance: 100,
      progress: 88,
      status: "Active",
      avatar: "C",
      color: "#e48788",
      photo: "CZ",
      feedback: {
        attitude: "Attentive",
        progress: "Excellent",
        comments:
          "Chloe completed all assigned work with clear reasoning and helped explain alternate solution paths during discussion.",
      },
    },
    {
      name: "Ethan Rivera",
      id: "40242",
      attendance: 91,
      progress: 79,
      status: "Active",
      avatar: "E",
      color: "#a78bfa",
      photo: "ER",
      feedback: {
        attitude: "Steady",
        progress: "Good",
        comments:
          "Ethan is consistent and prepared. Continue reinforcing proof notation.",
      },
    },
    {
      name: "Sophia Chen",
      id: "40247",
      attendance: 67,
      progress: 53,
      status: "Active",
      avatar: "S",
      color: "#f472b6",
      photo: "SC",
      feedback: {
        attitude: "Steady",
        progress: "Needs Improvement",
        comments: "Sophia should review core formulas before each session.",
      },
    },
    {
      name: "Noah Patel",
      id: "40251",
      attendance: 88,
      progress: 94,
      status: "Active",
      avatar: "N",
      color: "#34d399",
      photo: "NP",
      feedback: {
        attitude: "Attentive",
        progress: "Excellent",
        comments:
          "Noah works quickly and accurately. Add extension problems next week.",
      },
    },
    {
      name: "Emma Thompson",
      id: "40256",
      attendance: 45,
      progress: 38,
      status: "Inactive",
      avatar: "E",
      color: "#fb923c",
      photo: "ET",
      feedback: {
        attitude: "Distracted",
        progress: "Needs Improvement",
        comments: "Emma needs a recovery plan and consistent attendance.",
      },
    },
    {
      name: "James Kim",
      id: "40260",
      attendance: 95,
      progress: 91,
      status: "Active",
      avatar: "J",
      color: "#60a5fa",
      photo: "JK",
      feedback: {
        attitude: "Attentive",
        progress: "Excellent",
        comments: "James shows strong conceptual fluency.",
      },
    },
    {
      name: "Olivia Garcia",
      id: "40264",
      attendance: 78,
      progress: 62,
      status: "Active",
      avatar: "O",
      color: "#c084fc",
      photo: "OG",
      feedback: {
        attitude: "Steady",
        progress: "Good",
        comments: "Olivia is improving but should slow down on word problems.",
      },
    },
    {
      name: "Benjamin Lee",
      id: "40269",
      attendance: 82,
      progress: 71,
      status: "Active",
      avatar: "B",
      color: "#2dd4bf",
      photo: "BL",
      feedback: {
        attitude: "Steady",
        progress: "Good",
        comments: "Benjamin is building confidence with graph interpretation.",
      },
    },
    {
      name: "Ava Martinez",
      id: "40273",
      attendance: 56,
      progress: 44,
      status: "Inactive",
      avatar: "A",
      color: "#f87171",
      photo: "AM",
      feedback: {
        attitude: "Distracted",
        progress: "Needs Improvement",
        comments: "Ava needs a short daily practice routine.",
      },
    },
    {
      name: "Lucas Brown",
      id: "40278",
      attendance: 93,
      progress: 86,
      status: "Active",
      avatar: "L",
      color: "#38bdf8",
      photo: "LB",
      feedback: {
        attitude: "Attentive",
        progress: "Good",
        comments: "Lucas is ready for more challenging applications.",
      },
    },
    {
      name: "Mia Wilson",
      id: "40282",
      attendance: 74,
      progress: 69,
      status: "Active",
      avatar: "M",
      color: "#a3e635",
      photo: "MW",
      feedback: {
        attitude: "Steady",
        progress: "Good",
        comments: "Mia should keep practicing timed exercises.",
      },
    },
    {
      name: "Henry Davis",
      id: "40287",
      attendance: 89,
      progress: 83,
      status: "Active",
      avatar: "H",
      color: "#fbbf24",
      photo: "HD",
      feedback: {
        attitude: "Attentive",
        progress: "Good",
        comments: "Henry explains reasoning well in small groups.",
      },
    },
    {
      name: "Isabella Nguyen",
      id: "40291",
      attendance: 63,
      progress: 51,
      status: "Inactive",
      avatar: "I",
      color: "#e879f9",
      photo: "IN",
      feedback: {
        attitude: "Steady",
        progress: "Needs Improvement",
        comments: "Isabella needs extra review on prerequisites.",
      },
    },
    {
      name: "Alexander White",
      id: "40296",
      attendance: 97,
      progress: 95,
      status: "Active",
      avatar: "A",
      color: "#22c55e",
      photo: "AW",
      feedback: {
        attitude: "Attentive",
        progress: "Excellent",
        comments: "Alexander is performing at an advanced level.",
      },
    },
    {
      name: "Charlotte Harris",
      id: "40300",
      attendance: 71,
      progress: 58,
      status: "Active",
      avatar: "C",
      color: "#06b6d4",
      photo: "CH",
      feedback: {
        attitude: "Steady",
        progress: "Needs Improvement",
        comments: "Charlotte should focus on accuracy before speed.",
      },
    },
    {
      name: "Daniel Clark",
      id: "40305",
      attendance: 86,
      progress: 77,
      status: "Active",
      avatar: "D",
      color: "#f59e0b",
      photo: "DC",
      feedback: {
        attitude: "Steady",
        progress: "Good",
        comments: "Daniel is improving steadily.",
      },
    },
    {
      name: "Amelia Lewis",
      id: "40309",
      attendance: 52,
      progress: 41,
      status: "Inactive",
      avatar: "A",
      color: "#d946ef",
      photo: "AL",
      feedback: {
        attitude: "Distracted",
        progress: "Needs Improvement",
        comments: "Amelia needs structured review and follow-up.",
      },
    },
    {
      name: "Matthew Robinson",
      id: "40314",
      attendance: 94,
      progress: 90,
      status: "Active",
      avatar: "M",
      color: "#10b981",
      photo: "MR",
      feedback: {
        attitude: "Attentive",
        progress: "Excellent",
        comments: "Matthew completes work with strong accuracy.",
      },
    },
    {
      name: "Harper Walker",
      id: "40318",
      attendance: 69,
      progress: 55,
      status: "Active",
      avatar: "H",
      color: "#0ea5e9",
      photo: "HW",
      feedback: {
        attitude: "Steady",
        progress: "Needs Improvement",
        comments: "Harper should review missed questions after class.",
      },
    },
    {
      name: "David Hall",
      id: "40323",
      attendance: 81,
      progress: 74,
      status: "Active",
      avatar: "D",
      color: "#8b5cf6",
      photo: "DH",
      feedback: {
        attitude: "Steady",
        progress: "Good",
        comments: "David is consistent and asks useful questions.",
      },
    },
    {
      name: "Evelyn Allen",
      id: "40327",
      attendance: 77,
      progress: 65,
      status: "Active",
      avatar: "E",
      color: "#ec4899",
      photo: "EA",
      feedback: {
        attitude: "Steady",
        progress: "Good",
        comments: "Evelyn should keep building confidence with proofs.",
      },
    },
  ],
  materials: [
    {
      title: "Calculus Foundations: Limits & Continuity",
      type: "pdf",
      size: "4.2 MB",
      added: "OCT 12, 2023",
      description:
        "This core module covers the fundamental concepts of limits, continuity, and their applications in differential calculus. Ideal for Grade 12 students preparing for AP examinations.",
      category: "Worksheet",
      file: "calculus_limits.pdf",
    },
    {
      title: "Interactive Desmos Graph: Unit Circle",
      type: "link",
      size: "",
      added: "OCT 10, 2023",
      description:
        "Interactive visualization tool for exploring unit circle concepts and trigonometric functions dynamically.",
      category: "Reference",
      link: "https://www.desmos.com/calculator/unit-circle",
    },
    {
      title: "Homework Sheet 04: Trigonometric Identities",
      type: "doc",
      size: "850 KB",
      added: "OCT 08, 2023",
      description:
        "Comprehensive homework assignment covering trigonometric identities, proofs, and applications.",
      category: "Worksheet",
      file: "homework_sheet_04.docx",
    },
    {
      title: "Midterm Exam Review: Semester A",
      type: "pdf",
      size: "12.5 MB",
      added: "OCT 05, 2023",
      description:
        "Complete review guide for the first semester midterm exam with practice problems and solutions.",
      category: "Exam Material",
      file: "midterm_review_sem_a.pdf",
    },
    {
      title: "Visualizing Derivatives - 3Blue1Brown",
      type: "link",
      size: "",
      added: "OCT 02, 2023",
      description:
        "Award-winning educational video series explaining the intuition behind derivatives and calculus concepts.",
      category: "Video",
      link: "https://www.youtube.com/watch?v=9vKqVkMQHKc",
    },
  ],
  assignments: [
    {
      title: "Quadratic Equations Practice",
      subject: "Advanced Mathematics",
      grade: "Grade 10",
      posted: "Oct 12",
      postedFull: "Oct 12, 2023",
      deadline: "Oct 24, 11:59 PM",
      deadlineFull: "Oct 24, 2023 · 11:59 PM",
      submitted: 24,
      total: 28,
      graded: 18,
      avgScore: 88,
      urgent: true,
    },
    {
      title: "Trigonometry Basics Quiz",
      subject: "Advanced Mathematics",
      grade: "Grade 10",
      posted: "Oct 05",
      postedFull: "Oct 05, 2023",
      deadline: "Oct 15, 11:59 PM",
      deadlineFull: "Oct 15, 2023 · 11:59 PM",
      submitted: 28,
      total: 28,
      graded: 28,
      avgScore: 82,
      urgent: false,
    },
    {
      title: "Logarithmic Functions HW",
      subject: "Advanced Mathematics",
      grade: "Grade 10",
      posted: "Oct 26",
      postedFull: "Oct 26, 2023",
      deadline: "Oct 28",
      deadlineFull: "Oct 28, 2023 · 11:59 PM",
      submitted: 0,
      total: 28,
      graded: 0,
      avgScore: null,
      urgent: false,
    },
    {
      title: "Geometry Final Project Phase 1",
      subject: "Advanced Mathematics",
      grade: "Grade 10",
      posted: "Oct 18",
      postedFull: "Oct 18, 2023",
      deadline: "Nov 01, 11:59 PM",
      deadlineFull: "Nov 01, 2023 · 11:59 PM",
      submitted: 12,
      total: 28,
      graded: 5,
      avgScore: 76,
      urgent: true,
    },
  ],

  submissions: {
    "Quadratic Equations Practice": [
      { studentId: "40221", submittedAt: "Oct 22, 2023 · 4:15 PM", late: false, score: null, maxScore: 100, files: ["quadratic_julian.pdf"] },
      { studentId: "40225", submittedAt: "Oct 23, 2023 · 9:10 AM", late: false, score: null, maxScore: 100, files: ["maya_quadratic_practice.pdf"] },
      { studentId: "40230", submittedAt: "Oct 21, 2023 · 11:30 PM", late: false, score: 94, maxScore: 100, files: ["liam_hw3.pdf"] },
      { studentId: "40238", submittedAt: "Oct 24, 2023 · 2:05 PM", late: false, score: null, maxScore: 100, files: ["chloe_quadratic.pdf"] },
      { studentId: "40242", submittedAt: "Oct 24, 2023 · 8:44 PM", late: false, score: null, maxScore: 100, files: ["ethan_assignment3.pdf"] },
      { studentId: "40247", submittedAt: "Oct 25, 2023 · 1:02 AM", late: true,  score: 71, maxScore: 100, files: ["sophia_late_submission.pdf"] },
      { studentId: "40251", submittedAt: "Oct 22, 2023 · 6:30 PM", late: false, score: 98, maxScore: 100, files: ["noah_quadratic.pdf"] },
      { studentId: "40256", submittedAt: "Oct 23, 2023 · 3:15 PM", late: false, score: 85, maxScore: 100, files: ["emma_hw3.pdf"] },
      { studentId: "40260", submittedAt: "Oct 21, 2023 · 10:00 AM", late: false, score: 97, maxScore: 100, files: ["james_quadratic.pdf"] },
      { studentId: "40264", submittedAt: "Oct 24, 2023 · 11:45 PM", late: false, score: null, maxScore: 100, files: ["olivia_q3.pdf"] },
      { studentId: "40269", submittedAt: "Oct 23, 2023 · 7:20 PM", late: false, score: 88, maxScore: 100, files: ["ben_assignment3.docx"] },
      { studentId: "40273", submittedAt: "Oct 26, 2023 · 9:00 AM", late: true,  score: null, maxScore: 100, files: ["ava_late.pdf"] },
      { studentId: "40278", submittedAt: "Oct 22, 2023 · 5:00 PM", late: false, score: 91, maxScore: 100, files: ["lucas_quadratic.pdf"] },
      { studentId: "40282", submittedAt: "Oct 23, 2023 · 12:30 PM", late: false, score: 79, maxScore: 100, files: ["mia_hw3.pdf"] },
      { studentId: "40287", submittedAt: "Oct 24, 2023 · 9:55 AM", late: false, score: 86, maxScore: 100, files: ["henry_quadratic.pdf"] },
      { studentId: "40291", submittedAt: "Oct 24, 2023 · 4:00 PM", late: false, score: null, maxScore: 100, files: ["isabella_q3.pdf"] },
      { studentId: "40296", submittedAt: "Oct 20, 2023 · 3:40 PM", late: false, score: 100, maxScore: 100, files: ["alex_quadratic.pdf"] },
      { studentId: "40300", submittedAt: "Oct 24, 2023 · 10:30 PM", late: false, score: null, maxScore: 100, files: ["charlotte_hw3.pdf"] },
      { studentId: "40305", submittedAt: "Oct 23, 2023 · 2:00 PM", late: false, score: 83, maxScore: 100, files: ["daniel_quadratic.pdf"] },
      { studentId: "40309", submittedAt: "Oct 27, 2023 · 8:15 AM", late: true,  score: null, maxScore: 100, files: ["amelia_late_q3.pdf"] },
      { studentId: "40314", submittedAt: "Oct 22, 2023 · 11:00 AM", late: false, score: 95, maxScore: 100, files: ["matthew_q3.pdf"] },
      { studentId: "40318", submittedAt: "Oct 24, 2023 · 7:50 PM", late: false, score: null, maxScore: 100, files: ["harper_hw3.pdf"] },
      { studentId: "40323", submittedAt: "Oct 23, 2023 · 5:45 PM", late: false, score: 80, maxScore: 100, files: ["david_quadratic.pdf"] },
      { studentId: "40327", submittedAt: "Oct 24, 2023 · 6:10 PM", late: false, score: null, maxScore: 100, files: ["evelyn_hw3.pdf"] },
    ],
    "Trigonometry Basics Quiz": [
      { studentId: "40221", submittedAt: "Oct 14, 2023 · 8:00 PM", late: false, score: 90, maxScore: 100, files: ["julian_trig_quiz.pdf"] },
      { studentId: "40225", submittedAt: "Oct 15, 2023 · 10:30 AM", late: false, score: 78, maxScore: 100, files: ["maya_trig.pdf"] },
      { studentId: "40230", submittedAt: "Oct 15, 2023 · 11:00 PM", late: false, score: 65, maxScore: 100, files: ["liam_trig_quiz.pdf"] },
      { studentId: "40238", submittedAt: "Oct 13, 2023 · 2:00 PM", late: false, score: 96, maxScore: 100, files: ["chloe_trig.pdf"] },
      { studentId: "40242", submittedAt: "Oct 14, 2023 · 6:30 PM", late: false, score: 82, maxScore: 100, files: ["ethan_trig_quiz.pdf"] },
      { studentId: "40247", submittedAt: "Oct 15, 2023 · 9:45 PM", late: false, score: 74, maxScore: 100, files: ["sophia_trig.pdf"] },
      { studentId: "40251", submittedAt: "Oct 12, 2023 · 4:00 PM", late: false, score: 99, maxScore: 100, files: ["noah_trig_quiz.pdf"] },
      { studentId: "40256", submittedAt: "Oct 15, 2023 · 3:00 PM", late: false, score: 88, maxScore: 100, files: ["emma_trig.pdf"] },
      { studentId: "40260", submittedAt: "Oct 13, 2023 · 7:00 AM", late: false, score: 93, maxScore: 100, files: ["james_trig.pdf"] },
      { studentId: "40264", submittedAt: "Oct 14, 2023 · 5:20 PM", late: false, score: 70, maxScore: 100, files: ["olivia_trig_quiz.pdf"] },
      { studentId: "40269", submittedAt: "Oct 15, 2023 · 8:00 PM", late: false, score: 80, maxScore: 100, files: ["ben_trig.pdf"] },
      { studentId: "40273", submittedAt: "Oct 14, 2023 · 11:00 AM", late: false, score: 69, maxScore: 100, files: ["ava_trig_quiz.pdf"] },
      { studentId: "40278", submittedAt: "Oct 13, 2023 · 3:30 PM", late: false, score: 87, maxScore: 100, files: ["lucas_trig.pdf"] },
      { studentId: "40282", submittedAt: "Oct 15, 2023 · 1:15 PM", late: false, score: 76, maxScore: 100, files: ["mia_trig_quiz.pdf"] },
      { studentId: "40287", submittedAt: "Oct 14, 2023 · 9:00 AM", late: false, score: 85, maxScore: 100, files: ["henry_trig.pdf"] },
      { studentId: "40291", submittedAt: "Oct 15, 2023 · 6:45 PM", late: false, score: 72, maxScore: 100, files: ["isabella_trig_quiz.pdf"] },
      { studentId: "40296", submittedAt: "Oct 11, 2023 · 2:00 PM", late: false, score: 100, maxScore: 100, files: ["alex_trig.pdf"] },
      { studentId: "40300", submittedAt: "Oct 15, 2023 · 10:00 PM", late: false, score: 68, maxScore: 100, files: ["charlotte_trig.pdf"] },
      { studentId: "40305", submittedAt: "Oct 14, 2023 · 4:30 PM", late: false, score: 79, maxScore: 100, files: ["daniel_trig_quiz.pdf"] },
      { studentId: "40309", submittedAt: "Oct 15, 2023 · 7:30 PM", late: false, score: 61, maxScore: 100, files: ["amelia_trig.pdf"] },
      { studentId: "40314", submittedAt: "Oct 13, 2023 · 10:00 AM", late: false, score: 94, maxScore: 100, files: ["matthew_trig.pdf"] },
      { studentId: "40318", submittedAt: "Oct 15, 2023 · 5:00 PM", late: false, score: 73, maxScore: 100, files: ["harper_trig_quiz.pdf"] },
      { studentId: "40323", submittedAt: "Oct 14, 2023 · 3:00 PM", late: false, score: 77, maxScore: 100, files: ["david_trig.pdf"] },
      { studentId: "40327", submittedAt: "Oct 15, 2023 · 8:30 PM", late: false, score: 83, maxScore: 100, files: ["evelyn_trig_quiz.pdf"] },
      { studentId: "40256", submittedAt: "Oct 14, 2023 · 6:00 PM", late: false, score: 75, maxScore: 100, files: ["extra_trig.pdf"] },
      { studentId: "40278", submittedAt: "Oct 12, 2023 · 9:00 AM", late: false, score: 90, maxScore: 100, files: ["extra2_trig.pdf"] },
      { studentId: "40282", submittedAt: "Oct 13, 2023 · 4:00 PM", late: false, score: 84, maxScore: 100, files: ["extra3_trig.pdf"] },
      { studentId: "40323", submittedAt: "Oct 14, 2023 · 1:00 PM", late: false, score: 82, maxScore: 100, files: ["extra4_trig.pdf"] },
    ],
    "Geometry Final Project Phase 1": [
      { studentId: "40221", submittedAt: "Oct 30, 2023 · 3:00 PM", late: false, score: 88, maxScore: 100, files: ["julian_geo_p1.pdf", "julian_geo_p1_assets.zip"] },
      { studentId: "40225", submittedAt: "Oct 29, 2023 · 11:00 AM", late: false, score: null, maxScore: 100, files: ["maya_geo_phase1.pdf"] },
      { studentId: "40238", submittedAt: "Oct 28, 2023 · 5:30 PM", late: false, score: 92, maxScore: 100, files: ["chloe_geometry_p1.pdf"] },
      { studentId: "40242", submittedAt: "Oct 31, 2023 · 9:15 PM", late: false, score: null, maxScore: 100, files: ["ethan_geo.pdf"] },
      { studentId: "40251", submittedAt: "Oct 27, 2023 · 2:00 PM", late: false, score: 96, maxScore: 100, files: ["noah_geo_p1.pdf"] },
      { studentId: "40260", submittedAt: "Oct 30, 2023 · 10:00 AM", late: false, score: 89, maxScore: 100, files: ["james_geo_p1.pdf"] },
      { studentId: "40269", submittedAt: "Oct 29, 2023 · 4:45 PM", late: false, score: null, maxScore: 100, files: ["ben_geo_phase1.pdf"] },
      { studentId: "40278", submittedAt: "Oct 28, 2023 · 12:00 PM", late: false, score: null, maxScore: 100, files: ["lucas_geo.pdf"] },
      { studentId: "40287", submittedAt: "Oct 30, 2023 · 6:30 PM", late: false, score: null, maxScore: 100, files: ["henry_geo_p1.pdf"] },
      { studentId: "40296", submittedAt: "Oct 25, 2023 · 1:00 PM", late: false, score: 98, maxScore: 100, files: ["alex_geo_p1.pdf"] },
      { studentId: "40305", submittedAt: "Oct 31, 2023 · 7:00 PM", late: false, score: null, maxScore: 100, files: ["daniel_geo_phase1.pdf"] },
      { studentId: "40314", submittedAt: "Oct 29, 2023 · 8:30 AM", late: false, score: null, maxScore: 100, files: ["matthew_geo_p1.pdf"] },
    ],
  },
  sessions: [
    {
      date: "Oct 24, 2023",
      day: "Tuesday",
      time: "4:30 PM",
      status: "Completed",
      action: "View Roster",
    },
    {
      date: "Oct 26, 2023",
      day: "Thursday",
      time: "4:30 PM",
      status: "In Progress",
      action: "Take Attendance",
      current: true,
      today: true,
    },
    {
      date: "Oct 31, 2023",
      day: "Tuesday",
      time: "4:30 PM",
      status: "Scheduled",
      action: null,
    },
    {
      date: "Nov 02, 2023",
      day: "Thursday",
      time: "4:30 PM",
      status: "Scheduled",
      action: null,
    },
  ],
  weekDays: [
    { label: "MON", date: 14 },
    { label: "TUE", date: 15 },
    { label: "WED", date: 16, today: true },
    { label: "THU", date: 17 },
    { label: "FRI", date: 18 },
  ],
  timeSlots: [
    "08:00 AM",
    "09:00 AM",
    "10:00 AM",
    "11:00 AM",
    "12:00 PM",
    "01:00 PM",
    "02:00 PM",
    "03:00 PM",
    "04:00 PM",
    "05:00 PM",
    "06:00 PM",
    "07:00 PM",
  ],
  timetableEvents: [
    {
      id: "math-monday",
      title: "Advanced Mathematics",
      day: 0,
      startHour: 9,
      startMinute: 0,
      durationMinutes: 90,
      location: "Room 301",
      students: "12 Enrolled",
    },
    {
      id: "art-history",
      title: "Art History",
      day: 1,
      startHour: 14,
      startMinute: 0,
      durationMinutes: 90,
      location: "Studio B",
      students: "18 Enrolled",
    },
    {
      id: "math-thursday",
      title: "Advanced Mathematics",
      day: 3,
      startHour: 16,
      startMinute: 30,
      durationMinutes: 90,
      location: "Room 301",
      students: "12 Enrolled",
      active: true,
    },
  ],
  notifications: [
    {
      id: "notif-001",
      type: "room-change",
      title: "Room change: Advanced Mathematics",
      body: "Thursday's session at 4:30 PM has been moved from Room 301 to Room 205 due to maintenance. Please inform your students.",
      tag: "Schedule change",
      time: "2 MIN AGO",
      timestamp: "2023-10-26T16:28:00",
      read: false,
    },
    {
      id: "notif-002",
      type: "submission",
      title: "New submission: Quadratic Equations Practice",
      body: "Evelyn Allen (ID 40327) just submitted her work for Quadratic Equations Practice.",
      tag: "Submission",
      time: "14 MIN AGO",
      timestamp: "2023-10-26T16:16:00",
      read: false,
      meta: { studentName: "Evelyn Allen", studentId: "40327", assignment: "Quadratic Equations Practice" },
    },
    {
      id: "notif-003",
      type: "submission",
      title: "New submission: Quadratic Equations Practice",
      body: "Harper Walker (ID 40318) just submitted her work for Quadratic Equations Practice.",
      tag: "Submission",
      time: "31 MIN AGO",
      timestamp: "2023-10-26T15:59:00",
      read: false,
      meta: { studentName: "Harper Walker", studentId: "40318", assignment: "Quadratic Equations Practice" },
    },
    {
      id: "notif-004",
      type: "schedule",
      title: "Upcoming session: Advanced Mathematics",
      body: "You have a class session tomorrow, Thursday Oct 26 at 4:30 PM in Room 205 (updated). 12 students enrolled.",
      tag: "Schedule",
      time: "1 HOUR AGO",
      timestamp: "2023-10-26T15:30:00",
      read: false,
    },
    {
      id: "notif-005",
      type: "submission",
      title: "New submission: Geometry Final Project Phase 1",
      body: "Daniel Clark (ID 40305) submitted Geometry Final Project Phase 1.",
      tag: "Submission",
      time: "3 HOURS AGO",
      timestamp: "2023-10-26T13:00:00",
      read: true,
      meta: { studentName: "Daniel Clark", studentId: "40305", assignment: "Geometry Final Project Phase 1" },
    },
    {
      id: "notif-006",
      type: "room-change",
      title: "Room change: Art History",
      body: "Tuesday's Art History session has been relocated to Studio A. Original room Studio B is under renovation.",
      tag: "Schedule change",
      time: "5 HOURS AGO",
      timestamp: "2023-10-26T11:00:00",
      read: true,
    },
    {
      id: "notif-007",
      type: "submission",
      title: "New submission: Geometry Final Project Phase 1",
      body: "Matthew Robinson (ID 40314) submitted Geometry Final Project Phase 1 earlier than the deadline.",
      tag: "Submission",
      time: "YESTERDAY",
      timestamp: "2023-10-25T09:00:00",
      read: true,
      meta: { studentName: "Matthew Robinson", studentId: "40314", assignment: "Geometry Final Project Phase 1" },
    },
    {
      id: "notif-008",
      type: "schedule",
      title: "Session reminder: Art History",
      body: "Your Art History class (Studio A) is scheduled for Tuesday Nov 2 at 2:00 PM. 18 students enrolled.",
      tag: "Schedule",
      time: "YESTERDAY",
      timestamp: "2023-10-25T08:00:00",
      read: true,
    },
    {
      id: "notif-009",
      type: "submission",
      title: "Late submission: Quadratic Equations Practice",
      body: "Amelia Lewis (ID 40309) submitted Quadratic Equations Practice 2 days after the deadline.",
      tag: "Submission",
      time: "2 DAYS AGO",
      timestamp: "2023-10-24T08:15:00",
      read: true,
      meta: { studentName: "Amelia Lewis", studentId: "40309", assignment: "Quadratic Equations Practice", late: true },
    },
    {
      id: "notif-010",
      type: "schedule",
      title: "Upcoming session: Advanced Mathematics",
      body: "Reminder: Advanced Mathematics session on Tuesday Oct 31 at 4:30 PM in Room 301. Review lesson plan before class.",
      tag: "Schedule",
      time: "3 DAYS AGO",
      timestamp: "2023-10-23T09:00:00",
      read: true,
    },
    {
      id: "notif-011",
      type: "submission",
      title: "New submission: Geometry Final Project Phase 1",
      body: "Alexander White (ID 40296) submitted Geometry Final Project Phase 1 — submitted 6 days early.",
      tag: "Submission",
      time: "5 DAYS AGO",
      timestamp: "2023-10-21T13:00:00",
      read: true,
      meta: { studentName: "Alexander White", studentId: "40296", assignment: "Geometry Final Project Phase 1" },
    },
    {
      id: "notif-012",
      type: "room-change",
      title: "Room change: Advanced Mathematics (Oct 17)",
      body: "The Oct 17 session was held in Room 108 (temporary). Regular Room 301 resumes from Oct 24 onwards.",
      tag: "Schedule change",
      time: "1 WEEK AGO",
      timestamp: "2023-10-19T10:00:00",
      read: true,
    },
  ],
};

